### ISSUE TITLE
Receiving an error when running this command python3 main.py

### ISSUE THREAD

**Issue by edwardsalfred** [LukaHietala/RedditVideoMakerBot-website#15]
Traceback (most recent call last):
  File "/Users/alfrededwards/Desktop/RedditVideoMakerBot-master/main.py", line 11, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/Users/alfrededwards/Desktop/RedditVideoMakerBot-master/reddit/subreddit.py", line 11, in <module>
    from utils.subreddit import get_subreddit_undone
  File "/Users/alfrededwards/Desktop/RedditVideoMakerBot-master/utils/subreddit.py", line 6, in <module>
    from utils.ai_methods import sort_by_similarity
  File "/Users/alfrededwards/Desktop/RedditVideoMakerBot-master/utils/ai_methods.py", line 2, in <module>
    from transformers import AutoTokenizer, AutoModel
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1162, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1174, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tokenizers/tokenizers.cpython-311-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tokenizers/tokenizers.cpython-311-darwin.so: mach-o, but wrong architecture
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tokenizers/tokenizers.cpython-311-darwin.so: mach-o, but wrong architecture

**Comment by OpenSourceSimon** [comment]
This is the documentation repository.
